        !COMPILER-GENERATED INTERFACE MODULE: Wed May 15 19:06:37 2019
        MODULE FFTPACK_RFFTI1__genmod
          INTERFACE 
            SUBROUTINE FFTPACK_RFFTI1(N,WA,IFAC)
              INTEGER(KIND=4) :: N
              REAL(KIND=4) :: WA(N)
              INTEGER(KIND=4) :: IFAC(15)
            END SUBROUTINE FFTPACK_RFFTI1
          END INTERFACE 
        END MODULE FFTPACK_RFFTI1__genmod
