        !COMPILER-GENERATED INTERFACE MODULE: Wed May 15 19:06:37 2019
        MODULE FFTPACK_RFFTI__genmod
          INTERFACE 
            SUBROUTINE FFTPACK_RFFTI(N,WSAVE)
              INTEGER(KIND=4) :: N
              REAL(KIND=4) :: WSAVE(2*N+15)
            END SUBROUTINE FFTPACK_RFFTI
          END INTERFACE 
        END MODULE FFTPACK_RFFTI__genmod
