        !COMPILER-GENERATED INTERFACE MODULE: Wed May 15 19:07:03 2019
        MODULE QUICKSORT__genmod
          INTERFACE 
            SUBROUTINE QUICKSORT(N,X,IND)
              INTEGER(KIND=4), INTENT(IN) :: N
              REAL(KIND=4), INTENT(IN) :: X(N)
              INTEGER(KIND=4), INTENT(INOUT) :: IND(N)
            END SUBROUTINE QUICKSORT
          END INTERFACE 
        END MODULE QUICKSORT__genmod
