        !COMPILER-GENERATED INTERFACE MODULE: Wed May 15 19:06:37 2019
        MODULE TIMESTAMP__genmod
          INTERFACE 
            SUBROUTINE TIMESTAMP(TIMESTRING)
              CHARACTER(LEN=72), INTENT(OUT) :: TIMESTRING
            END SUBROUTINE TIMESTAMP
          END INTERFACE 
        END MODULE TIMESTAMP__genmod
