        !COMPILER-GENERATED INTERFACE MODULE: Wed May 15 19:06:37 2019
        MODULE WRITE_LOGFILE__genmod
          INTERFACE 
            SUBROUTINE WRITE_LOGFILE
            END SUBROUTINE WRITE_LOGFILE
          END INTERFACE 
        END MODULE WRITE_LOGFILE__genmod
