#!/bin/bash

username=`logname`
echo $username

/home/Guoqing.Ge/local/bin/git config user.name "${username}"
/home/Guoqing.Ge/local/bin/git config user.email "guoqing.ge@noaa.gov"

/home/Guoqing.Ge/local/bin/git commit "$@"
echo "Do you want to push the commit to the server (y/n)?"
read YN
if [[ "$YN"="y" ]]; then
   ./rtrrpush
else
   "The commit is not pushed to server. Run './rtrrpush' to do the push"
fi

/home/Guoqing.Ge/local/bin/git config --unset user.name
/home/Guoqing.Ge/local/bin/git config --unset user.email
