        !COMPILER-GENERATED INTERFACE MODULE: Wed May 15 19:01:15 2019
        MODULE GETORDER__genmod
          INTERFACE 
            SUBROUTINE GETORDER(FLNM1,FLNM2,FLLEVTYP1,FLLEVTYP2,FLLEV1, &
     &FLLEV2,NREC,ORDER)
              INTEGER(KIND=4) :: NREC
              CHARACTER(LEN=16) :: FLNM1(NREC)
              CHARACTER(LEN=16) :: FLNM2(NREC)
              CHARACTER(LEN=16) :: FLLEVTYP1(NREC)
              CHARACTER(LEN=16) :: FLLEVTYP2(NREC)
              INTEGER(KIND=4) :: FLLEV1(NREC)
              INTEGER(KIND=4) :: FLLEV2(NREC)
              INTEGER(KIND=4), INTENT(OUT) :: ORDER(NREC)
            END SUBROUTINE GETORDER
          END INTERFACE 
        END MODULE GETORDER__genmod
