        !COMPILER-GENERATED INTERFACE MODULE: Wed May 15 19:01:13 2019
        MODULE INIT_SIGDATA__genmod
          INTERFACE 
            SUBROUTINE INIT_SIGDATA(HEAD,DATA)
              USE SIGIO_MODULE
              TYPE (SIGIO_HEAD), INTENT(IN) :: HEAD
              TYPE (SIGIO_DATA), INTENT(INOUT) :: DATA
            END SUBROUTINE INIT_SIGDATA
          END INTERFACE 
        END MODULE INIT_SIGDATA__genmod
