        !COMPILER-GENERATED INTERFACE MODULE: Wed May 15 19:01:13 2019
        MODULE SMOOTH__genmod
          INTERFACE 
            SUBROUTINE SMOOTH(SPECDAT,NTRUNC,NLEVS,SMOOTHPARM,WINDOW)
              INTEGER(KIND=4), INTENT(IN) :: NLEVS
              INTEGER(KIND=4), INTENT(IN) :: NTRUNC
              REAL(KIND=4), INTENT(INOUT) :: SPECDAT((NTRUNC+1)*(NTRUNC+&
     &2),NLEVS)
              INTEGER(KIND=4), INTENT(IN) :: SMOOTHPARM(NLEVS)
              INTEGER(KIND=4), INTENT(IN) :: WINDOW
            END SUBROUTINE SMOOTH
          END INTERFACE 
        END MODULE SMOOTH__genmod
