#!/bin/bash
module load rocoto
xmlfile=RTMA_3D

t1=`date -u +"%Y%m%d%H00"`
echo "current cycle: $t1"
tt1=`echo $t1 |cut -c1-8`
tt2=`echo $t1 |cut -c9-10`
t_m1=`date -u -d "$tt1 $tt2 -1 hour" +%Y%m%d%H00`
t_m2=`date -u -d "$tt1 $tt2 -2 hour" +%Y%m%d%H00`
t_m3=`date -u -d "$tt1 $tt2 -3 hour" +%Y%m%d%H00`
echo $t_m1
echo $t_m2
echo $t_m3

rstat () {
rocotostat -w $1.xml -d $1.db
}
rstatct () {
rocotostat -w $1.xml -d $1.db -c $2 -t '$3'
}

cycles="$t1,$t_m1,$t_m2,$t_m3"
#rstatct  $xmlfile $curCycle  wrf_arw_short,wrf_arw_medium,wrf_arw_long,gsi_hyb
rocotostat -w ${xmlfile}.xml -d ${xmlfile}.db -c $cycles -t 'gsi_hyb,satellite_gsi_bufr,satellite_gsi,conventional_gsi,conventional_gsi_early,gsi_diag,smartinit_bl,smartinit_nb,post_00,ncl_00,ncl_zp,ncl_skewt_zp,ncl_htxs_zp'


