#!/bin/ksh

# --- for debug --- #
date
export PS4=' $SECONDS + ' 
set -x

#######################################################
# The following variable could be defined in the 
# submission script (the ecf script *.sms, or ROCOTO *.xml),
# if not, they will take the default values which is set 
# for the NCO running enviroment
#######################################################


# Set the path to the gsi executable
export LIGHTNING=${GSI_ROOT}/process_Lightning.exe

# Make sure DATAHOME is defined and exists
if [ ! "${DATAHOME}" ]; then
  ${ECHO} "ERROR: \$DATAHOME is not defined!"
  exit 1
fi
if [ ! -d "${DATAHOME}" ]; then
  ${ECHO} "Warning: DATAHOME directory '${DATAHOME}' does not exist!"
fi

if [ ! "${DATAROOT}" ]; then
  ${ECHO} "ERROR: \$DATAROOT is not defined!"
  exit 1
fi
if [ ! -d "${DATAROOT}" ]; then
  ${ECHO} "ERROR: DATAROOT directory '${DATAROOT}' does not exist!"
  exit 1
fi
if [ ! -d "${LIGHTNING_ROOT}" ]; then
  ${ECHO} "ERROR: LIGHTNING_ROOT directory '${LIGHTNING_ROOT}' does not exist!"
  exit 1
fi

# Make sure sub-hourly time is defined and exists
if [ ! "${SUBH_TIME}" ]; then
  ${ECHO} "ERROR: \$SUBH_TIME is not defined!"
  exit 1
fi

# Make sure GSI_ROOT is defined and exists
if [ ! "${GSI_ROOT}" ]; then
  ${ECHO} "ERROR: \$GSI_ROOT is not defined!"
  exit 1
fi
if [ ! -d "${GSI_ROOT}" ]; then
  ${ECHO} "ERROR: GSI_ROOT directory '${GSI_ROOT}' does not exist!"
  exit 1
fi



# Make sure START_TIME is defined and in the correct format
if [ ! "${START_TIME}" ]; then
  ${ECHO} "ERROR: \$START_TIME is not defined!"
  exit 1
else
  if [ `${ECHO} "${START_TIME}" | ${AWK} '/^[[:digit:]]{10}$/'` ]; then
    export START_TIME=`${ECHO} "${START_TIME}" | ${SED} 's/\([[:digit:]]\{2\}\)$/ \1/'`
  elif [ ! "`${ECHO} "${START_TIME}" | ${AWK} '/^[[:digit:]]{8}[[:blank:]]{1}[[:digit:]]{2}$/'`" ]; then
    ${ECHO} "ERROR: start time, '${START_TIME}', is not in 'yyyymmddhh' or 'yyyymmdd hh' format"
    exit 1
  fi
export START_TIME=`${DATE} -d "${START_TIME} ${SUBH_TIME} minutes"`
fi


# Make sure the GSI executable exists

if [ ! -x "${LIGHTNING}" ]; then

  ${ECHO} "ERROR: ${LIGHTNING} does not exist!"

  exit 1

fi

# Create the obsprd directory if necessary and cd into it

if [ ! -d "${DATAHOME}" ]; then

  ${MKDIR} -p ${DATAHOME}

fi

cd ${DATAHOME}

if [ -x "process_Lightning.exe" ]; then

  ${RM} process_Lightning.exe

fi


#####################
# Execute the script.
######################
# ${exSCR_LIGHTNING:-$HOMErtma3d/scripts/${RUN}/ex${RUN}_lightning.ksh}
${HOMErtma3d}/scripts/exrtma3d_lightning.ksh
export err=$?; err_chk

msg="$0 of $job completed normally"
postmsg $jlogfile "$msg"

date

set +x
