        !COMPILER-GENERATED INTERFACE MODULE: Wed May 15 19:04:30 2019
        MODULE INT2_MSK_GLB_PREP__genmod
          INTERFACE 
            SUBROUTINE INT2_MSK_GLB_PREP(A,ISLI_A,B,ISLI_B,NX,NY,       &
     &SFCTYP_B,NPREP)
              INTEGER(KIND=4), INTENT(IN) :: NY
              INTEGER(KIND=4), INTENT(IN) :: NX
              REAL(KIND=8), INTENT(IN) :: A(NX,NY)
              INTEGER(KIND=4), INTENT(IN) :: ISLI_A(NX,NY)
              REAL(KIND=8), INTENT(OUT) :: B(NX,NY)
              INTEGER(KIND=4), INTENT(OUT) :: ISLI_B(NX,NY)
              INTEGER(KIND=4), INTENT(IN) :: SFCTYP_B
              INTEGER(KIND=4), INTENT(IN) :: NPREP
            END SUBROUTINE INT2_MSK_GLB_PREP
          END INTERFACE 
        END MODULE INT2_MSK_GLB_PREP__genmod
