        !COMPILER-GENERATED INTERFACE MODULE: Wed May 15 19:04:30 2019
        MODULE INT22_MSK_GLB__genmod
          INTERFACE 
            SUBROUTINE INT22_MSK_GLB(A,ISLI_A,RLATS_A,RLONS_A,NLAT_A,   &
     &NLON_A,B,ISLI_B,RLATS_B,RLONS_B,NLAT_B,NLON_B,ISTYP)
              INTEGER(KIND=4), INTENT(IN) :: NLON_B
              INTEGER(KIND=4), INTENT(IN) :: NLAT_B
              INTEGER(KIND=4), INTENT(IN) :: NLON_A
              INTEGER(KIND=4), INTENT(IN) :: NLAT_A
              REAL(KIND=8), INTENT(IN) :: A(NLAT_A,NLON_A)
              INTEGER(KIND=4), INTENT(IN) :: ISLI_A(NLAT_A,NLON_A)
              REAL(KIND=8), INTENT(IN) :: RLATS_A(NLAT_A)
              REAL(KIND=8), INTENT(IN) :: RLONS_A(NLON_A)
              REAL(KIND=8), INTENT(OUT) :: B(NLAT_B,NLON_B)
              INTEGER(KIND=4), INTENT(IN) :: ISLI_B(NLAT_B,NLON_B)
              REAL(KIND=8), INTENT(IN) :: RLATS_B(NLAT_B)
              REAL(KIND=8), INTENT(IN) :: RLONS_B(NLON_B)
              INTEGER(KIND=4), INTENT(IN) :: ISTYP
            END SUBROUTINE INT22_MSK_GLB
          END INTERFACE 
        END MODULE INT22_MSK_GLB__genmod
