setenv("rtma_ver","v2.9.0")
setenv("COMP","ftn")
setenv("FC","ftn")
setenv("COMP_MP","ftn")
setenv("COMP_MPI","ftn")
local envvar_ver = os.getenv("envvar_ver")
local PrgEnv_intel_ver = os.getenv("PrgEnv_intel_ver")
local intel_ver = os.getenv("intel_ver")
local libjpeg_ver = os.getenv("libjpeg_ver")
local craype_ver = os.getenv("craype_ver")
local cray_mpich_ver = os.getenv("cray_mpich_ver")
local cray_pals_ver = os.getenv("cray_pals_ver")
local prod_util_ver = os.getenv("prod_util_ver") 
local cmake_ver = os.getenv("cmake_ver")
local ip_ver = os.getenv("ip_ver")
local bacio_ver = os.getenv("bacio_ver")
local w3nco_ver = os.getenv("w3nco_ver")
local w3emc_ver = os.getenv("w3emc_ver")
local g2_ver = os.getenv("g2_ver")
local jasper_ver = os.getenv("jasper_ver")
local libpng_ver = os.getenv("libpng_ver")
local zlib_ver = os.getenv("zlib_ver")
local bufr_ver = os.getenv("bufr_ver")
local sp_ver = os.getenv("sp_ver")
local crtm_ver = os.getenv("crtm_ver")
local nemsio_ver = os.getenv("nemsio_ver")
local netcdf_ver = os.getenv("netcdf_ver")
local hdf5_ver = os.getenv("hdf5_ver")
local sfcio_ver = os.getenv("sfcio_ver")
local sigio_ver = os.getenv("sigio_ver")
local wgrib2_ver = os.getenv("wgrib2_ver")


load("envvar/"..envvar_ver)
load("PrgEnv-intel/"..PrgEnv_intel_ver)
load("intel/"..intel_ver)
load("libjpeg/"..libjpeg_ver)
load("craype/"..craype_ver)
load("cray-mpich/"..cray_mpich_ver)
load("cray-pals/"..cray_pals_ver)
load("prod_util/"..prod_util_ver) 
load("cmake/"..cmake_ver)
load("ip/"..ip_ver)
load("bacio/"..bacio_ver)
load("w3nco/"..w3nco_ver)
load("w3emc/"..w3emc_ver)
load("g2/"..g2_ver)
load("jasper/"..jasper_ver)
load("libpng/"..libpng_ver)
load("zlib/"..zlib_ver)
load("bufr/"..bufr_ver)
load("sp/"..sp_ver)
load("crtm/"..crtm_ver)
load("nemsio/"..nemsio_ver)
load("netcdf/"..netcdf_ver)
load("hdf5/"..hdf5_ver)
load("sfcio/"..sfcio_ver)
load("sigio/"..sigio_ver)
load("sp/"..sp_ver)
load("wgrib2/"..wgrib2_ver)


