#!/bin/sh 

# --- for debug --- #
date
export PS4=' $SECONDS + '
set -xa
export MP_IOAGENT_CNT=all
export MP_IO_BUFFER_SIZE=8M

##################################################
# 3DRTMA generation of input files for sounding post 
##################################################

######################################################
# The following variable could be defined in the
# submission script (the ecf script *.sms, or ROCOTO *.xml),
# if not, they will take the default values which is set
# for the NCO running enviroment
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-nco}

###################################
# Specify NET and RUN Name
####################################
export NET=${NET:-rtma3d}
export RUN=${RUN:-rtma3d}

####################################
# Define data and shared directories
####################################
export DATA=${DATA:-$DATAROOT/${jobid:?}}
export DATA_SHARED=${DATA_SHARED:-${DATAROOT}/sharedprd}
mkdir -p $DATA $DATA_SHARED
cd $DATA

#####################################################
# Run setpdy and initialize PDY variables
#    setpdy.sh needs the variables 
#    $PDY and $cyc already defined in advance
#####################################################
export cycle=${cycle:-t${cyc}z}
setpdy.sh
. ./PDY

export CDATE="${PDY}${cyc}"

export pgmout=${pgmout:-"OUTPUT.$$"}

####################################
# Specify Execution Areas
####################################
export HOMErtma3d=${HOMErtma3d:-$PACKAGEROOT/${NET}.${rtma3d_ver}}
export EXECrtma3d=${EXECrtma3d:-$HOMErtma3d/exec}
export FIXrtma3d=${FIXrtma3d:-$HOMErtma3d/fix/${dom}}
export PARMrtma3d=${PARMrtma3d:-$HOMErtma3d/parm/${dom}}
export USHrtma3d=${USHrtma3d:-$HOMErtma3d/ush/${dom}}

##############################################
# Set up the INPUT and OUTPUT directories
##############################################
export COMIN=${COMIN:-$(compath.py  ${envir}/${NET}/${rtma3d_ver})/${RUN}.${PDY}/${dom}}
export COMOUT=${COMOUT:-$(compath.py -o  ${envir}/${NET}/${rtma3d_ver})/${RUN}.${PDY}/${dom}}
export COMINm1=${COMINm1:-$(compath.py -o  ${envir}/${NET}/${rtma3d_ver})/${RUN}.${PDYm1}/${dom}}

mkdir -p $COMOUT

env

########################################################
# Execute the script.
$HOMErtma3d/scripts/${dom}/ex${RUN}_wrfbufr.ksh
export err=$?; err_chk
########################################################

postmsg "$0 of $job completed normally"

if [ -e "${pgmout}" ] ; then
   cat $pgmout
fi

##############################
# Remove the Temporary working directory
##############################
if [ "${KEEPDATA}" != YES ]; then
   rm -rf $DATA
fi

date

