#!/bin/ksh 
set -xa
export MP_IOAGENT_CNT=all
export MP_IO_BUFFER_SIZE=8M

##################################################
# HRRR generation of input files for sounding post 
##################################################

######################################################
# The following two variable could be defined in the
# loadleveler submission script (the sms script), if
# not they will take the default values which is set
# for the NCO running enviroment
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-nco}

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-hrrr}
export RUN=${RUN:-hrrr}
export model=${model:-hrrr}

#####################################################################################
# This block is for Developer's test run:
# Run config file to get input parameters
# This config file should define the following variables
# DATA_IN: Location of working directory, default to ${DATAROOT}
# SENDECF: If the job is to be running using ECF, default to YES
# SENDDBN: Set to NO for developers, default to YES
# COM_IN:  Directory for input files, default to ${COMROOT}/$NET/${envir}
# COM_OUT: Directory for output file, default to ${COMROOT}/$NET/${envir}
# gespath: Directory for the guess or restart files, default to ${GESROOT}/${envir}
#####################################################################################
#if [ "$RUN_ENVIR" != nco ]      ### For Developers, "group_name" is passed from the ECF script
#then
#  group_name=${group_name:-meso}
#  package_name=${package_name:-hrrr}
##  . /${group_name}/save/${LOGNAME}/${package_name}${PACKAGEROOT}/parm/${package_name}_para_config
#  export userid=${userid:-$LOGNAME}
#fi

export PS4='$SECONDS + '
date

####################################
# obtain unique process id (pid) and make temp directory
####################################
export DATATMP=${DATATMP:-${DATAROOT}/pbspro/${NET}.${PDY}${cyc}00/bufrsnd}
if [ -d $DATATMP ] ; then
   ${ECHO} "$DATATMP exists, remove its content"
     ${RM} -rf $DATATMP/*
else
   ${ECHO} "$DATATMP does not exist, create it"
   ${MKDIR} -p $DATATMP
fi 
cd $DATATMP

export cycle=t${cyc}z

export pgmout="OUTPUT.$$"

####################################
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy files to /com directory
####################################
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}

####################################
# Specify Execution Areas
####################################

export cycm1=`expr $cyc - 1`
if [ "$cyc" = 00 ]; then
cycm1=23
else
cycm1=$(printf "%02d" $cycm1)
fi

export cyclem1=t${cycm1}z

export PDYHH=${PDY}${cyc}
export PDYHH_cycm1=$($NDATE -01  "${PDYHH}")
PDYm1=`echo ${PDYHH_cycm1} | cut -c 1-8`

export HOMErtma3d=${HOMErtma3d:-$NWROOT/rtma.${rtma_ver}}
export EXECrtma3d=${EXECrtma3d:-$HOMErtma3d/exec}
export FIXrtma3d=${FIXrtma3d:-$HOMErtma3d/fix/${NET}}
export PARMrtma3d=${PARMrtma3d:-$HOMErtma3d/parm/${NET}}
export USHrtma3d=${USHrtma3d:-$HOMErtma3d/ush/${NET}}
export UTILrtma3d=${UTILrtma3d:-$HOMErtma3d/util/${NET}}


##############################################
# Define COM directories
##############################################

# for WCOSS2 ops
export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/${NET}.${PDY}}
export COMINm1=${COMINm1:-${COMROOT}/${NET}/${envir}/${NET}.${PDYm1}}
export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${NET}.${PDY}}
export COMOUTm1=${COMOUTm1:-${COMROOT}/${NET}/${envir}/${NET}.${PDYm1}}
### Observations Products/Input for the RTMA3D (prepbufr files) 
export COMINobsproc_rtma3d=${COMINobsproc_rtma3d:-"${COMIN}/obsprd.${cycle}"}
export COMINobsproc_rtma3dm1=${COMINobsproc_rtma3dm1:-"${COMINm1}/obsprd.${cycle}"}

### Firstguess Products/Input for the RTMA3D (netcdf) 
export GESINhrrr_rtma3d=${GESINhrrr_rtma3d:-"${COMIN}/fgsprd.${cycle}"}

### 3DRTMA GSIANL Products (netcdf)
export COMOUTgsi_rtma3d=${COMOUTgsi_rtma3d:-"${COMOUT}/gsiprd.${cycle}"}
export COMOUTgsi_rtma3dm1=${COMOUTgsi_rtma3dm1:-"${COMOUTm1}/gsiprd.${cyclem1}"}


### 3DRTMA UNI-POST Products (grib2)
export COMOUTpost_rtma3d=${COMOUTpost_rtma3d:-"${COMOUT}/postprd.${cycle}"}


if [ ! -d "${COMIN}" ] ; then
   mkdir -p $COMIN
fi
if [ ! -d "${COMOUT}" ] ; then
   mkdir -p $COMOUT
fi

export COM_IN=${COM_IN:-$COMROOT/${NET}/${envir}}


env

########################################################
# Execute the script.
${HRRR_WRFBUFRSH:-$HOMErtma3d/scripts/${RUN}/ex${RUN}_wrfbufr.ksh}
########################################################

cat $pgmout

msg="ENDED NORMALLY."
postmsg "$jlogfile" "$msg"

export KEEPDATA=YES
##############################
# Remove the Temporary working directory
##############################
#cd $DATATMP
#if [ ${KEEPDATA} = NO ] ; then rm -rf $DATATMP ; fi

date

