#!/bin/ksh

# --- for debug --- #
date
export PS4=' $SECONDS + ' 
set -x

#######################################################
# The following variable could be defined in the 
# submission script (the ecf script *.sms, or ROCOTO *.xml),
# if not, they will take the default values which is set 
# for the NCO running enviroment
#######################################################


######################
# Execute the script.
######################
# ${exSCR_GSI_HYB:-$HOMErtma3d/scripts/${RUN}/ex${RUN}_gsi_hyb.ksh}
${HOMErtma3d}/scripts/exrtma3d_gsi_hyb.ksh
export err=$?; err_chk

msg="$0 of $job completed normally"
postmsg $jlogfile "$msg"

date

set +x
