#!/bin/ksh

# --- for debug --- #
date
export PS4=' $SECONDS + ' 
set -x

#######################################################
# The following variable could be defined in the 
# submission script (the ecf script *.sms, or ROCOTO *.xml),
# if not, they will take the default values which is set 
# for the NCO running enviroment
#######################################################

export jlogfile=${jlogfile:-"${LOG_DIR}/jlogfile_${PDY}${cyc}"}

######################
# Execute the script.
######################
# ${exSCR_SATELLITE_BUFR:-$HOMErtma3d/scripts/${RUN}/ex${RUN}_satellite_bufr.ksh}
${HOMErtma3d}/scripts/exrtma3d_satellite_bufr.ksh
export err=$?; err_chk

msg="$0 of $job completed normally"
postmsg $jlogfile "$msg"

date

set +x
