#!/bin/ksh

##########################################################
# This job...
# 
########################################################

date
export PS4=' $SECONDS + ' 
set -x

#######################################################
# The following variable could be defined in the
# submission script (the ecf script), if
# not they will take the default values which is set
# for the NCO running enviroment
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-nco}

#################
# Set NET and RUN
#################
export NET=rtma3d

# Note: grib_util module loaded in submission (lsf or ecFlow) script

##########################################################
export pgmout=${pgmout:-"OUTPUT.${PDY}${cyc}.${jobid}"}
export jlogfile=${jlogfile:-$COMROOT/logs/jlogfiles/jlogfile.$jobid}
####################################
# Determine Job Output Name on Sstem
####################################
export LOG_JJOB=${LOG_JJOB:-$COMROOT/logs/jlogfiles}
export jlogfile=${jlogfile:-$LOG_JJOB/jlogfile.${jobid}}
if [ ! -d ${LOG_JJOB} ] ; then
   mkdir -p ${LOG_JJOB}
fi
if [ ! -d ${LOG_PGMOUT} ] ; then
   mkdir -p ${LOG_PGMOUT}
fi

# Specify Execution Areas
export HOMErtma3d=${HOMErtma3d:-$PACKAGEROOT/${NET}.${rtma3d_ver}}

# date and time for previous and next cycle
export PDYHH="${PDY}${cyc}"

# creating a sub-directory under top running directory to share the data among various steps
#   DATA_RUNDIR: the top running directory
export DATA_RUNDIR=${DATA_RUNDIR:-"${DATAROOT}/${envir}/${NET}.${PDY}${cyc}"}
if [ ! -d "${DATA_RUNDIR}" ] ; then
    mkdir -p ${DATA_RUNDIR}
fi
#   DATA_SHARED: the sub-directory to share the data
export DATA_SHARED=${DATA_SHARED:-"${DATA_RUNDIR}/sharedprd"}
if [ ! -d "${DATA_SHARED}" ] ; then
    mkdir -p ${DATA_SHARED}
fi

# running the executable script
${exSCR_CLEAN:-$HOMErtma3d/scripts/ex${NET}_clean.ksh}
export err=$?; err_chk

msg="$0 of $job completed normally"
postmsg $jlogfile "$msg"


if [ -e "${pgmout}" ] ; then
   cat $pgmout
   cpreq -p $pgmout ${LOG_PGMOUT}
fi

postmsg $jlogfile "$0 of $job completed normally"


date
