#!/bin/ksh

date
export PS4=' $SECONDS + ' 
set -x

#module load cfp/2.0.4

#######################################################
# The following variable could be defined in the 
# submission script (the ecf script *.sms, or ROCOTO *.xml),
# if not, they will take the default values which is set 
# for the NCO running enviroment
#######################################################

export RUN_ENVIR=${RUN_ENVIR:-nco}

###################################
# Specify NET and RUN Name
####################################
export NET=${NET:-rtma3d}
#export RUN=rtma3d, akrtma3d ! Set in ecf script instead of j-job

##########################################################
# obtain unique process id (pid)
##########################################################
export job=${job:-"${outid}.o$$"}
export jobid=${jobid:-"${outid}.o$$"}
export MPIRUN=${MPIRUN:-"mpirun"}

##########################################################
# make temp/running directories
##########################################################
export DATA=${DATA:-$DATAROOT/${jobid:?}} #jobid ($job.$LSB_JOBID MUST BE DEFINED IN TERMS OF $RUN IN UPPER LEVEL SCRIPT /MPondeca, 26Jul2015

mkdir -p $DATA
cd $DATA

#####################################################
# Run setpdy and initialize PDY variables
#    setpdy.sh needs the variables 
#    $PDY and $cyc already defined in advance
#####################################################
#setpdy.sh
#. ./PDY

export cycle=t${cyc}z

####################################
# Determine Job Output Name on System
####################################
export pgmout=${pgmout:-"OUTPUT.$$"}

####################################
# Determine Job Output Name on System
####################################
export LOG_JJOB=${LOG_JJOB:-$COMROOT/logs/jlogfiles}
export jlogfile=${jlogfile:-$LOG_JJOB/jlogfile.${jobid}}
if [ ! -d ${LOG_JJOB} ] ; then
   mkdir -p ${LOG_JJOB}
fi
if [ ! -d ${LOG_PGMOUT} ] ; then
   mkdir -p ${LOG_PGMOUT}
fi

# Specify Execution Areas
export HOMErtma3d=${HOMErtma3d:-${PACKAGEROOT}/${NET}.${rtma3d_ver}}
export HOMEscript=${HOMEscript:-${HOMErtma3d}/scripts}
export EXECrtma3d=${EXECrtma3d:-$HOMErtma3d/exec}
export FIXrtma3d=${FIXrtma3d:-$HOMErtma3d/fix/${dom}}
export PARMrtma3d=${PARMrtma3d:-$HOMErtma3d/parm/${dom}}
export USHrtma3d=${USHrtma3d:-$HOMErtma3d/ush/${dom}}

#################################################
# Set up the INPUT and OUTPUT directories
# Set up paths for input model data
#################################################
export COMIN=${COMIN:-$(compath.py  ${envir}/${NET}/${rtma3d_ver})/${RUN}.${PDY}/${dom}}
export COMOUT=${COMOUT:-$(compath.py -o  ${envir}/${NET}/${rtma3d_ver})/${RUN}.${PDY}/${dom}}
export seaice_analysis_ver=v4.5
export COMINsice=${COMINsice:-$(compath.py prod/seaice_analysis/${seaice_analysis_ver})}

mkdir -p $COMOUT

env

######################
# Execute the script.
######################
#$HOMErtma3d/scripts/${RUN}/ex${RUN}_prdgen.sh
$HOMErtma3d/scripts/${dom}/ex${RUN}_prdgen.ksh
export err=$?; err_chk

msg="$0 of $job completed normally"
postmsg $jlogfile "$msg"

if [ -e "${pgmout}" ] ; then
   cat $pgmout
   cpreq -p $pgmout ${LOG_PGMOUT}
fi

##############################
# Remove the Temporary working directory
##############################
if [ "${KEEPDATA}" != YES ]; then
   rm -rf $DATA
fi

date
