#!/bin/ksh

##########################################################
# This job...
# 
########################################################

date
export PS4=' $SECONDS + ' 
set -x

#######################################################
# The following variable could be defined in the
# submission script (the ecf script), if
# not they will take the default values which is set
# for the NCO running enviroment
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-nco}

#################
# Set NET and RUN
#################
export NET=rtma3d

KEEPDATA="YES"
# Note: grib_util module loaded in submission (lsf or ecFlow) script

##########################################################
export jobid=${jobid:-"${outid}.o$$"}
export DATA=${DATA:-$DATAROOT/${jobid:?}} #jobid ($job.$LSB_JOBID MUST BE DEFINED IN TERMS OF $RUN IN UPPER LEVEL SCRIPT /MPondeca, 26Jul2015
if [ -d $DATA ] ; then
   rm  -rf $DATA/*
else
   mkdir -p $DATA	 
fi
cd $DATA

export cycle=${cycle:-t${cyc}z}
export pgmout=${pgmout:-"OUTPUT.${PDY}${cyc}.${jobid}"}


export jlogfile=${jlogfile:-$COMROOT/logs/jlogfiles/jlogfile.$jobid}
####################################
# Determine Job Output Name on Sstem
####################################
export LOG_JJOB=${LOG_JJOB:-$COMROOT/logs/jlogfiles}
export jlogfile=${jlogfile:-$LOG_JJOB/jlogfile.${jobid}}
if [ ! -d ${LOG_JJOB} ] ; then
   mkdir -p ${LOG_JJOB}
fi
if [ ! -d ${LOG_PGMOUT} ] ; then
   mkdir -p ${LOG_PGMOUT}
fi

# specify the file head for the file names of the archived data files
export PROD_HEAD=${PROD_HEAD:-"${NET}.${cycle}"}


# Specify Execution Areas
export HOMErtma3d=${HOMErtma3d:-$NWROOT/rtma.${rtma_ver}}
export EXECrtma3d=${EXECrtma3d:-$HOMErtma3d/exec}
export FIXrtma3d=${FIXrtma3d:-$HOMErtma3d/fix/${NET}}
export PARMrtma3d=${PARMrtma3d:-$HOMErtma3d/parm/${NET}}
export USHrtma3d=${USHrtma3d:-$HOMErtma3d/ush/${NET}}
export UTILrtma3d=${UTILrtma3d:-$HOMErtma3d/util/${NET}}

# date and time for previous and next cycle
export PDYHH="${PDY}${cyc}"
export PDYHH_cycm1=$($NDATE -01  "${PDYHH}")


#################################################
# Set up the INPUT and OUTPUT directories
#################################################
### COM_IN used to retrieve ges and analysis files from 2p5, ak, gu, hi, and pr
export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/${NET}.${PDY}}
export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${NET}.${PDY}}
export COMOUTgsi_rtma3d=${COMOUTgsi_rtma3d:-"${COMOUT}/gsiprd.${cycle}"}
export COMOUThrrrdas_rtma3d=${COMOUThrrrdas_rtma3d:-"${COMOUT}/hrrrdas.${cycle}"}
if [ ! -d "${COMOUThrrrdas_rtma3d}" ] ; then
  mkdir -p ${COMOUThrrrdas_rtma3d}
fi
if [ ! -d "${COMIN}" ] ; then
   mkdir -p $COMIN
fi
if [ ! -d "${COMOUT}" ] ; then
   mkdir -p $COMOUT
fi


export COM_IN=${COM_IN:-$COMROOT/${NET}/${envir}}

${exSCR_HRRRDAS:-$HOMErtma3d/scripts/${RUN}/ex${RUN}_hrrrdas.ksh}
export err=$?; err_chk

msg="$0 of $job completed normally"
postmsg $jlogfile "$msg"


if [ -e "${pgmout}" ] ; then
   cat $pgmout
   cpreq -p $pgmout ${LOG_PGMOUT}
fi

postmsg $jlogfile "$0 of $job completed normally"

if [ "${KEEPDATA}" != YES ]; then
    rm -rf $DATA
fi

date
