#!/bin/sh

# --- for debug --- #
date
export PS4=' $SECONDS + ' 
set -x

#######################################################
# The following variable could be defined in the 
# submission script (the ecf script *.sms, or ROCOTO *.xml),
# if not, they will take the default values which is set 
# for the NCO running enviroment
#######################################################

export RUN_ENVIR=${RUN_ENVIR:-nco}

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-rtma3d}
export RUN=${RUN:-rtma3d}
export model=${model:-rtma3d}

##########################################################
# obtain unique process id (pid)
##########################################################
export job=${job:-"${outid}.o$$"}
export jobid=${jobid:-"${outid}.o$$"}
export MPIRUN=${MPIRUN:-"mpirun"}

export CNVGRIB=${CNVGRIB:-cnvgrib}

##########################################################
# make temp/running directories
##########################################################
export DATA=${DATA:-$DATAROOT/${jobid:?}} #jobid ($job.$LSB_JOBID MUST BE DEFINED IN TERMS OF $RUN IN UPPER LEVEL SCRIPT /MPondeca, 26Jul2015
if [ -d $DATA ] ; then
   rm  -rf $DATA/*
else
   mkdir -p $DATA
fi
cd $DATA

#####################################################
# Run setpdy and initialize PDY variables
#    setpdy.sh needs the variables 
#    $PDY and $cyc already defined in advance
#####################################################
export cycle=${cycle:-t${cyc}z} 
setpdy.sh
. ${DATA}/PDY

export subcyc=${subcyc} #Note: Must define subcyc in upper level script. Can be 00, 15, 30, or 45 /MPondeca, 30Jun2017
                         #only used for rurtma2p5
export PDYHH="${PDY}${cyc}"
####################################
# Determine Job Output Name on System
####################################
export LOG_JJOB=${LOG_JJOB:-$COMROOT/logs/jlogfiles}
export jlogfile=${jlogfile:-$LOG_JJOB/jlogfile.${jobid}}
export pgmout=${pgmout:-"OUTPUT.$$"}
if [ ! -d ${LOG_JJOB} ] ; then
   mkdir -p ${LOG_JJOB}
fi
if [ ! -d ${LOG_PGMOUT} ] ; then
   mkdir -p ${LOG_PGMOUT}
fi

# Specify Execution Areas
export HOMErtma3d=${HOMErtma3d:-$NWROOT/rtma.${rtma_ver}}
export EXECrtma3d=${EXECrtma3d:-$HOMErtma3d/exec}
export FIXrtma3d=${FIXrtma3d:-$HOMErtma3d/fix/${RUN}}
export PARMrtma3d=${PARMrtma3d:-$HOMErtma3d/parm/${RUN}}
export USHrtma3d=${USHrtma3d:-$HOMErtma3d/ush/${RUN}}

# date and time for previous and next cycle
export PDYHH_cycm1=`$EXECrtma3d/ndate.x -1 "${PDYHH}"`
export PDYHH_cycm1=$($NDATE -01  "${PDYHH}")
export PDYHH_cycp1=`$EXECrtma3d/ndate.x +1 "${PDYHH}"`
export PDYHH_cycp1=$($NDATE +01  "${PDYHH}")
echo $PDYHH
echo ${PDYHH_cycm1}
echo ${PDYHH_cycp1}

export FGS_OPT=${FGS_OPT:-1}

#################################################
# Set up the INPUT and OUTPUT directories
#################################################
export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}

### Observations Products/Input from RAP
export COMINrap=${COMINrap:-"${COMIN}/rap.${PDY}"}
export COMINrap_e=${COMINrap:-"${COMIN}/rap_e.${PDY}"}
export COMINhrrr=${COMINhrrr:-"${COMIN}/hrrr.${PDY}/conus"}
export COMINlightning=${COMINlightning:-"${COMIN}/lightning.${PDY}"}
export COMINmosaic=${COMINmosaic:-"${COMIN}/radar.${PDY}"}
export COMINradar=${COMINradar:-"${COMIN}/radar.${PDY}"}

### Observations Products/Input for the RTMA3D (prepbufr files) 
export COMINobsproc_rtma3d=${COMINobsproc_rtma3d:-"${COMIN}/obsprd.${cycle}"}

### Firstguess Products/Input for the RTMA3D (prepbufr files) 
export GESINhrrr_rtma3d=${GESINhrrr_rtma3d:-"${COMIN}/fgsprd.${cycle}"}

if [ ! -d "${COMIN}" ] ; then
   mkdir -p $COMIN
fi
if [ ! -d "${COMOUT}" ] ; then
   mkdir -p $COMOUT
fi
if [ ! -d "${COMINobsproc_rtma3d}" ] ; then
# echo " Directory of obs data does NOT exist. Job abort!"
# err_exit
  mkdir -p $COMINobsproc_rtma3d
fi

###########################################################
#
# The following variables are used in exrtma3d_obsprep_radar.sh
#
###########################################################

#   Set the path to the executable
    export MOSAIC_EXEDIR=${MOSAIC_EXEDIR:-"${EXECrtma3d}"}
    export MOSAIC_EXE=${MOSAIC_EXE:-"process_NSSL_mosaic.exe"}
    export MOSAIC=${MOSAIC:-"${MOSAIC_EXEDIR}/${MOSAIC_EXE}"}

#   Set the path to the GSI static files
#   export FIX_ROOT=${FIXrtma3d:?} 
    export fixdir=${FIX_GSI:-"${FIXrtma3d}/GSI-fix"}
    export CRTMFIX=${FIX_CRTM:-"${FIXrtma3d}/CRTM-fix"}
    export WRFPARM=${PARM_WRF:-"${FIXrtma3d}/WRF-parm"}
    export OBS_USELIST=${OBS_USELIST:-"${FIXrtma3d}/CRTM-fix"}

    export SFCOBS_USELIST=${SFCOBS_USELIST:-"${FIXrtma3d}/ObsUseList/gsd/mesonet_uselists"}
    export AIRCRAFT_REJECT=${AIRCRAFT_REJECT:-"${FIXrtma3d}/ObsUseList/gsd/amdar_reject_lists"}
    export SFCOBS_PROVIDER=${SFCOBS_PROVIDER:-"${FIXrtma3d}/GSI-fix"}

##########################################################

######################
# Execute the script.
######################
${exSCR_OBSPREP_RADAR:-$HOMErtma3d/scripts/${RUN}/ex${RUN}_obsprep_radar.sh}
export err=$?; err_chk

msg="$0 of $job completed normally"
postmsg $jlogfile "$msg"

if [ -e "${pgmout}" ] ; then
   cat $pgmout
   cp -p $pgmout   ${LOG_PGMOUT}
fi

##############################
# Remove the Temporary working directory
##############################
if [ "${KEEPDATA}" != YES ]; then
   rm -rf $DATA
fi

date
