#!/bin/ksh
set -x

echo 'into launchPTYPE'
. /usrx/local/prod/lmod/lmod/init/sh
source /u/${USER}/.bashrc

if [ ! -d /gpfs/dell2/stmp/${USER}/rtma3dda/${YMD}/$cyc$subcyc ] ; then
mkdir -p /gpfs/dell2/stmp/${USER}/rtma3dda/${YMD}/$cyc$subcyc
fi

cd /gpfs/dell2/stmp/${USER}/rtma3dda/${YMD}/$cyc$subcyc

python /gpfs/dell2/emc/modeling/noscrub/${USER}/python.rtma3d/compare_da/plot_rtma3d_ptype__dif.py $CDATE 
wait

exit
