#!/bin/ksh
set -x

echo 'into launchALL'
. /usrx/local/prod/lmod/lmod/init/sh
source /u/${USER}/.bashrc


module load python/3.6.3
module use -a /u/Benjamin.Blake/modulefiles
module load python3/test
export GRIB_DEFINITION_PATH=/usrx/local/nceplibs/dev/lib/grib_api/share/grib_api/definitions
export PYTHONPATH="${PYTHONPATH}:/gpfs/dell2/emc/verification/noscrub/Logan.Dawson/python:/gpfs/dell2/emc/modeling/noscrub/Jacob.Carley/python/lib/python3.6/site-packages
"


if [ ! -d /gpfs/dell1/ptmp/${USER}/rtma3dda/${YMD} ] ; then
mkdir -p /gpfs/dell1/ptmp/${USER}/rtma3dda/${YMD}
fi

cd /gpfs/dell1/ptmp/${USER}/rtma3dda/${YMD}

python /gpfs/dell2/emc/modeling/noscrub/${USER}/python.rtma3d/compare_da/plot_alldomains1.py $CDATE 

exit


