       SUBROUTINE W3FB11_8(ALAT,ELON,ALAT1,ELON1,DX,ELONV,ALATAN,XI,XJ)
!$$$   SUBPROGRAM  DOCUMENTATION  BLOCK
!
! SUBPROGRAM:  W3FB11        LAT/LON TO LAMBERT(I,J) FOR GRIB
!   PRGMMR: STACKPOLE        ORG: NMC42       DATE:88-11-28
!
! ABSTRACT: CONVERTS THE COORDINATES OF A LOCATION ON EARTH GIVEN IN
!   THE NATURAL COORDINATE SYSTEM OF LATITUDE/LONGITUDE TO A GRID
!   COORDINATE SYSTEM OVERLAID ON A LAMBERT CONFORMAL TANGENT CONE
!   PROJECTION TRUE AT A GIVEN N OR S LATITUDE. W3FB11 IS THE REVERSE
!   OF W3FB12. USES GRIB SPECIFICATION OF THE LOCATION OF THE GRID
!
! PROGRAM HISTORY LOG:
!   88-11-25  ORIGINAL AUTHOR:  STACKPOLE, W/NMC42
!   90-04-12  R.E.JONES   CONVERT TO CFT77 FORTRAN
!   94-04-28  R.E.JONES   ADD SAVE STATEMENT
!
! USAGE:  CALL W3FB11 (ALAT,ELON,ALAT1,ELON1,DX,ELONV,ALATAN,XI,XJ)
!   INPUT ARGUMENT LIST:
!     ALAT     - LATITUDE IN DEGREES (NEGATIVE IN SOUTHERN HEMIS)
!     ELON     - EAST LONGITUDE IN DEGREES, REAL*4
!     ALAT1    - LATITUDE  OF LOWER LEFT POINT OF GRID (POINT (1,1))
!     ELON1    - LONGITUDE OF LOWER LEFT POINT OF GRID (POINT (1,1))
!                ALL REAL*4
!     DX       - MESH LENGTH OF GRID IN METERS AT TANGENT LATITUDE
!     ELONV    - THE ORIENTATION OF THE GRID.  I.E.,
!                THE EAST LONGITUDE VALUE OF THE VERTICAL MERIDIAN
!                WHICH IS PARALLEL TO THE Y-AXIS (OR COLUMNS OF
!                OF THE GRID) ALONG WHICH LATITUDE INCREASES AS
!                THE Y-COORDINATE INCREASES.  REAL*4
!                THIS IS ALSO THE MERIDIAN (ON THE BACK SIDE OF THE
!                TANGENT CONE) ALONG WHICH THE CUT IS MADE TO LAY
!                THE CONE FLAT.
!     ALATAN   - THE LATITUDE AT WHICH THE LAMBERT CONE IS TANGENT TO
!                (TOUCHING) THE SPHERICAL EARTH.
!                 SET NEGATIVE TO INDICATE A
!                 SOUTHERN HEMISPHERE PROJECTION.
!
!   OUTPUT ARGUMENT LIST:
!     XI       - I COORDINATE OF THE POINT SPECIFIED BY ALAT, ELON
!     XJ       - J COORDINATE OF THE POINT; BOTH REAL*4
!
!   REMARKS: FORMULAE AND NOTATION LOOSELY BASED ON HOKE, HAYES,
!     AND RENNINGER'S "MAP PROJECTIONS AND GRID SYSTEMS...", MARCH 1981
!     AFGWC/TN-79/003
!
! ATTRIBUTES:
!   LANGUAGE: CRAY CFT77 FORTRAN
!   MACHINE:  CRAY C916-128, CRAY Y-MP8/864, CRAY Y-MP EL2/256
!
!$$$
!
         SAVE
!
         REAL*8 ALAT,ELON,ALAT1,ELON1,DX,ELONV,ALATAN,XI,XJ
         DATA  RERTH /6.3712E+6/, PI/3.14159/
!
!        PRELIMINARY VARIABLES AND REDIFINITIONS
!
!        H = 1 FOR NORTHERN HEMISPHERE; = -1 FOR SOUTHERN
!
         IF (ALATAN.GT.0) THEN
           H = 1.
         ELSE
           H = -1.
         ENDIF
!
!         print *,'ALAT,ELON,ALAT1,ELON1,DX,ELONV,ALATAN,XI,XJ=',ALAT,ELON,ALAT1,ELON1,DX,ELONV,ALATAN,XI,XJ
         RADPD  = PI    / 180.0
         REBYDX = RERTH / DX
         ALATN1 = ALATAN * RADPD
         AN     = H * SIN(ALATN1)
         COSLTN = COS(ALATN1)
!
!        MAKE SURE THAT INPUT LONGITUDES DO NOT PASS THROUGH
!        THE CUT ZONE (FORBIDDEN TERRITORY) OF THE FLAT MAP
!        AS MEASURED FROM THE VERTICAL (REFERENCE) LONGITUDE.
!
         ELON1L = ELON1
         IF ((ELON1 - ELONV).GT.180.)  ELON1L = ELON1 - 360.
         IF ((ELON1 - ELONV).LT.(-180.)) ELON1L = ELON1 + 360.
!
         ELONL = ELON
         IF ((ELON  - ELONV).GT.180.) ELONL  = ELON  - 360.
         IF ((ELON - ELONV).LT.(-180.)) ELONL = ELON + 360.
!
         ELONVR = ELONV * RADPD
!
!        RADIUS TO LOWER LEFT HAND (LL) CORNER
!
         ALA1 =  ALAT1 * RADPD
         RMLL = REBYDX * (((COSLTN)**(1.-AN))*(1.+AN)**AN) *&
                (((COS(ALA1))/(1.+H*SIN(ALA1)))**AN)/AN
!
!        USE LL POINT INFO TO LOCATE POLE POINT
!
         ELO1 = ELON1L * RADPD
         ARG = AN * (ELO1-ELONVR)
         POLEI = 1. - H * RMLL * SIN(ARG)
         POLEJ = 1. + RMLL * COS(ARG)
!
!        RADIUS TO DESIRED POINT AND THE I J TOO
!
         ALA =  ALAT * RADPD
         RM = REBYDX * ((COSLTN**(1.-AN))*(1.+AN)**AN) *&
                (((COS(ALA))/(1.+H*SIN(ALA)))**AN)/AN
!
         ELO = ELONL * RADPD
         ARG = AN*(ELO-ELONVR)
         XI = POLEI + H * RM * SIN(ARG)
         XJ = POLEJ - RM * COS(ARG)
!         print *,'XI=',POLEI
!
!        IF COORDINATE LESS THAN 1
!        COMPENSATE FOR ORIGIN AT (1,1)
!
         IF (XI.LT.1.)  XI = XI - 1.
         IF (XJ.LT.1.)  XJ = XJ - 1.
!
      RETURN
      END
