      SUBROUTINE W3FB08_8(ALAT,ALON,ALAT1,ALON1,ALATIN,DX,XI,XJ)
!$$$   SUBPROGRAM  DOCUMENTATION  BLOCK
!
! SUBPROGRAM:  W3FB08        LAT/LON TO MERC (I,J) FOR GRIB
!   PRGMMR: STACKPOLE        ORG: NMC42       DATE:88-04-05
!
! ABSTRACT: CONVERTS A LOCATION ON EARTH GIVEN IN
!   THE COORDINATE SYSTEM OF LATITUDE/LONGITUDE TO AN (I,J)
!   COORDINATE SYSTEM OVERLAID ON A MERCATOR MAP PROJECTION
!   W3FB08 IS THE REVERSE OF W3FB09
!   USES GRIB SPECIFICATION OF THE LOCATION OF THE GRID
!
! PROGRAM HISTORY LOG:
!   88-03-01  ORIGINAL AUTHOR:  STACKPOLE, W/NMC42
!   90-04-12  R.E.JONES   CONVERT TO CRAY CFT77 FORTRAN
!
! USAGE:  CALL W3FB08 (ALAT,ALON,ALAT1,ALON1,ALATIN,DX,XI,XJ)
!   INPUT ARGUMENT LIST:
!     ALAT     - LATITUDE IN DEGREES (NEGATIVE IN SOUTHERN HEMIS)
!     ALON     - EAST LONGITUDE IN DEGREES, REAL*4
!     ALAT1    - LATITUDE  OF LOWER LEFT CORNER OF GRID (POINT (1,1))
!     ALON1    - LONGITUDE OF LOWER LEFT CORNER OF GRID (POINT (1,1))
!                ALL REAL*4
!     ALATIN   - THE LATITUDE AT WHICH THE MERCATOR CYLINDER
!                INTERSECTS THE EARTH
!     DX       - MESH LENGTH OF GRID IN METERS AT ALATIN
!
!   OUTPUT ARGUMENT LIST:
!     XI       - I COORDINATE OF THE POINT SPECIFIED BY ALAT, ALON
!     XJ       - J COORDINATE OF THE POINT; BOTH REAL*4
!
!   REMARKS: FORMULAE AND NOTATION LOOSELY BASED ON HOKE, HAYES,
!     AND RENNINGER'S "MAP PROJECTIONS AND GRID SYSTEMS...", MARCH 1981
!     AFGWC/TN-79/003
!
! ATTRIBUTES:
!   LANGUAGE: CRAY CFT77 FORTRAN
!   MACHINE:  CRAY Y-MP8/832
!
!$$$
!
         REAL ALAT,ALON,ALAT1,ALON1,ALATIN,DX,XI,XJ,DJEO
         DATA  RERTH /6.3712E+6/, PI/3.1416/
!
!        PRELIMINARY VARIABLES AND REDIFINITIONS
!
         RADPD  = PI    / 180.0
         DEGPR  = 180.0 / PI
         CLAIN  = COS(RADPD*ALATIN)
         DELLON = DX   / (RERTH*CLAIN)
!
!        GET DISTANCE FROM EQUATOR TO ORIGIN ALAT1
!
         DJEO = 0.
         IF (ALAT1.NE.0.)&
          DJEO = (ALOG(TAN(0.5*((ALAT1+90.0)*RADPD))))/DELLON
!
!        NOW THE I AND J COORDINATES
!
         XI = 1. + ((ALON - ALON1)/(DELLON*DEGPR))
         XJ = 1. + (ALOG(TAN(0.5*((ALAT + 90.) * RADPD))))/&
                    DELLON&
                  - DJEO
!
      RETURN
      END

