#!/bin/ksh
set -x

#USER=Benjamin.Blake
#CDATE=2018103000
#cyc=00

echo 'into launchREF1KM'
. /usrx/local/prod/lmod/lmod/init/sh
source /u/${USER}/.bashrc

mkdir -p /gpfs/dell2/stmp/${USER}
mkdir -p /gpfs/dell2/stmp/${USER}/fv3da
mkdir -p /gpfs/dell2/stmp/${USER}/fv3da/$cyc
cd /gpfs/dell2/stmp/${USER}/fv3da/$cyc

python /gpfs/dell2/emc/modeling/noscrub/${USER}/python.fv3/compare_da/plot_fv3_ref1km_${domain}_dif.py $CDATE
#python /gpfs/dell2/emc/modeling/noscrub/${USER}/python.fv3/compare_da/plot_fv3_ref1km_conus_dif.py $CDATE &
#python /gpfs/dell2/emc/modeling/noscrub/${USER}/python.fv3/compare_da/plot_fv3_ref1km_NC_dif.py $CDATE &
#python /gpfs/dell2/emc/modeling/noscrub/${USER}/python.fv3/compare_da/plot_fv3_ref1km_NE_dif.py $CDATE &
#python /gpfs/dell2/emc/modeling/noscrub/${USER}/python.fv3/compare_da/plot_fv3_ref1km_NW_dif.py $CDATE &
#python /gpfs/dell2/emc/modeling/noscrub/${USER}/python.fv3/compare_da/plot_fv3_ref1km_OV_dif.py $CDATE &
#python /gpfs/dell2/emc/modeling/noscrub/${USER}/python.fv3/compare_da/plot_fv3_ref1km_SC_dif.py $CDATE &
#python /gpfs/dell2/emc/modeling/noscrub/${USER}/python.fv3/compare_da/plot_fv3_ref1km_SE_dif.py $CDATE &
#python /gpfs/dell2/emc/modeling/noscrub/${USER}/python.fv3/compare_da/plot_fv3_ref1km_SW_dif.py $CDATE &
#python /gpfs/dell2/emc/modeling/noscrub/${USER}/python.fv3/compare_da/plot_fv3_ref1km_UM_dif.py $CDATE &
wait

exit
