local envvar_ver = os.getenv("envvar_ver")
local PrgEnv_intel_ver = os.getenv("PrgEnv_intel_ver")
local intel_ver = os.getenv("intel_ver")
local craype_ver = os.getenv("craype_ver")
local cray_mpich_ver = os.getenv("cray_mpich_ver")
local hdf5_ver = os.getenv("hdf5_ver")
local netcdf_ver = os.getenv("netcdf_ver")
local pnetcdf_ver = os.getenv("pnetcdf_ver")
local cray_pals_ver = os.getenv("cray_pals_ver")
local ip_ver = os.getenv("ip_ver")
local bacio_ver = os.getenv("bacio_ver")
local w3emc_ver = os.getenv("w3emc_ver")
local g2_ver = os.getenv("g2_ver")
local g2tmpl_ver = os.getenv("g2tmpl_ver")
local jasper_ver = os.getenv("jasper_ver")
local zlib_ver = os.getenv("zlib_ver")
local udunits_ver = os.getenv("udunits_ver")
local gsl_ver = os.getenv("gsl_ver")
local nco_ver = os.getenv("nco_ver")
local nemsio_ver = os.getenv("nemsio_ver")
local bufr_ver = os.getenv("bufr_ver")
local sfcio_ver = os.getenv("sfcio_ver")
local sp_ver = os.getenv("sp_ver")
local sigio_ver = os.getenv("sigio_ver")
local gfsio_ver = os.getenv("gfsio_ver")
local esmf_ver = os.getenv("esmf_ver")
local crtm_ver = os.getenv("crtm_ver")
local libpng_ver = os.getenv("libpng_ver")
local libxmlparse_ver = os.getenv("libxmlparse_ver")
local libjpeg_ver = os.getenv("libjpeg_ver")
local wrf_io_ver = os.getenv("wrf_io_ver")
local cmake_ver = os.getenv("cmake_ver")
local git_ver = os.getenv("git_ver")

load("envvar/"..envvar_ver)
load("PrgEnv-intel/"..PrgEnv_intel_ver)
load("craype/"..craype_ver)
load("intel/"..intel_ver)
load("cray-mpich/"..cray_mpich_ver)
load("hdf5/"..hdf5_ver)
load("netcdf/"..netcdf_ver)
load("pnetcdf/"..pnetcdf_ver)
load("cray-pals/"..cray_pals_ver)
load("ip/"..ip_ver)
load("bacio/"..bacio_ver)
load("w3emc/"..w3emc_ver)
load("g2/"..g2_ver)
load("g2tmpl/"..g2tmpl_ver)
load("jasper/"..jasper_ver)
load("zlib/"..zlib_ver)
load("udunits/"..udunits_ver)
load("gsl/"..gsl_ver)
load("nco/"..nco_ver)
load("nemsio/"..nemsio_ver)
load("bufr/"..bufr_ver)
load("sfcio/"..sfcio_ver)
load("sp/"..sp_ver)
load("sigio/"..sigio_ver)
load("gfsio/"..gfsio_ver)
load("esmf/"..esmf_ver)
load("crtm/"..crtm_ver)
load("libpng/"..libpng_ver)
load("libxmlparse/"..libxmlparse_ver)
load("libjpeg/"..libjpeg_ver)
load("wrf_io/"..wrf_io_ver)
load("cmake/"..cmake_ver)
load("git/"..git_ver)
