#!/bin/ksh
set -x

USER=Benjamin.Blake
CDATE=2019030500
cyc=00
fhr=60

echo 'into launchALL'
. /usrx/local/prod/lmod/lmod/init/sh
source /u/${USER}/.bashrc

mkdir -p /gpfs/dell2/stmp/${USER}
mkdir -p /gpfs/dell2/stmp/${USER}/rtma3dda
mkdir -p /gpfs/dell2/stmp/${USER}/rtma3dda/$cyc
cd /gpfs/dell2/stmp/${USER}/rtma3dda/$cyc

python /gpfs/dell2/emc/modeling/noscrub/${USER}/python.fv3/compare_da/plot_alldomains1.py $CDATE $fhr

exit


